plugins:
  neo4j_twitter_script:
    client: true
    default: 'https://platform.twitter.com/widgets.js'
  neo4j_twitter_handle_url:
    client: true
    default: 'https://twitter.com/neo4j?ref_src=twsrc%5Etfw'
  neo4j_twitter_height:
    client: true
    default: 294
  neo4j_twitter_width:
    client: true
    default: 220
  neo4j_blog_url:
    client: false
    default: 'https://neo4j.com'
  neo4j_blog_post_filter_tag_id:
    client: true
    default: 3201
  neo4j_latest_announcements_category:
    client: true
    default: ''
    type: category_list
    list_type: "compact"