plugins:
  neo4j_twitter_script:
    client: true
    default: 'https://platform.twitter.com/widgets.js'
  neo4j_twitter_handle_url:
    client: true
    default: 'https://twitter.com/neo4j?ref_src=twsrc%5Etfw'
  neo4j_twitter_height:
    client: true
    default: 294
  neo4j_twitter_width:
    client: true
    default: 220
  neo4j_blog_url:
    client: false
    default: 'https://neo4j.com'
  neo4j_blog_post_filter_tag_id:
    client: true
    default: 3201
  neo4j_latest_announcements_category:
    client: true
    default: ''
    type: category_list
    list_type: "compact"
  neo4j_latest_announcements_number_of_entries:
    client: true
    default: 5
    max: 10
    min: 1
  neo4j_can_you_help_search_criteria:
    client: true
    default: 'q=status%3Anoreplies%20after%3A14%20-tags%3Aknowledge-base%20in%3Aunseen%20order%3Alatest'
  neo4j_can_you_help_number_of_entries:
    client: true
    default: 6
    min: 6
    max: 6
  neo4j_community_content_category:
    client: true
    default: ''
    type: category_list
    list_type: "compact"
  neo4j_community_content_number_of_entries:
    client: true
    default: 3
    max: 3
    min: 3
  neo4j_community_projects_category:
    client: true
    default: ''
    type: category_list
    list_type: "compact"
  neo4j_community_projects_number_of_entries:
    client: true
    default: 3
    max: 3
    min: 3
  neo4j_meet_new_members_category:
    client: true
    default: ''
    type: category_list
    list_type: "compact"
  neo4j_meet_new_members_number_of_entries:
    client: true
    default: 3
    max: 3
    min: 3
  neo4j_certified_devs_group:
    client: true
    default: ''
    type: group_list
    list_type: "compact"
  neo4j_certified_devs_number_of_entries:
    client: true
    default: 3
    max: 3
    min: 3
  neo4j_useful_links:
    client: true
    default: "Main Site,https://neo4j.com|The Blog,https://neo4j.com/blog"
    type: list
    allow_any: true
  neo4j_graph_gear_store_links:
    client: true
    default: "Main Site,https://neo4j.com|The Blog,https://neo4j.com/blog"
    type: list
    allow_any: true
  neo4j_jobs_links:
    client: true
    default: "Main Site,https://neo4j.com|The Blog,https://neo4j.com/blog"
    type: list
    allow_any: true
  neo4j_newbie_links:
    client: true
    default: "Main Site,https://neo4j.com|The Blog,https://neo4j.com/blog"
    type: list
    allow_any: true
  neo4j_share_feedback_links:
    client: true
    default: "Main Site,https://neo4j.com|The Blog,https://neo4j.com/blog"
    type: list
    allow_any: true
